apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert -f docker-compose-resolved.yaml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Kompose\kompose-windows-amd64.exe convert -f docker-compose-resolved.yaml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: REACT_APP_BASEURL
          value: https://somosbluecity.es:4000
        - name: REACT_APP_CLIENT_ID
          value: 1047982378803-uk51kj7li5dpttm5kclc8uf3ri59fljh.apps.googleusercontent.com
        image: bluecity_app
        name: app
        ports:
        - containerPort: 3000
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
