networks:
  app-network:
    driver: bridge
services:
  api:
    build:
      context: D:\Casa\bluecity-test-last\bluecity-test\backend
    environment:
      BLUECITY_CLIENT: https://somosbluecity.es
      DB_DATABASE: bluecity_dev
      DB_DIALECT: mysql
      DB_HOST: db
      DB_PASSWORD: SasaSasera1
      DB_ROOT_PASSWORD: SasaSasera1
      DB_USER: root
      JWT_SECRET: V3RY#1MP0RT@NT$$3CR3T#
      MYSQL_DATABASE: bluecity_dev
      MYSQL_PASSWORD: SasaSasera1
      MYSQL_ROOT_PASSWORD: SasaSasera1
      MYSQL_USER: root
      NODE_ENV: development
    expose:
    - '4000'
    image: bluecity_api
    networks:
      app-network: null
    ports:
    - published: 4000
      target: 4000
  app:
    build:
      context: D:\Casa\bluecity-test-last\bluecity-test\frontend
    environment:
      REACT_APP_BASEURL: https://somosbluecity.es:4000
      REACT_APP_CLIENT_ID: 1047982378803-uk51kj7li5dpttm5kclc8uf3ri59fljh.apps.googleusercontent.com
    expose:
    - '3000'
    image: bluecity_app
    networks:
      app-network: null
    ports:
    - published: 3000
      target: 3000
    stdin_open: true
    tty: true
  db:
    environment:
      BLUECITY_CLIENT: https://somosbluecity.es
      DB_DATABASE: bluecity_dev
      DB_DIALECT: mysql
      DB_HOST: db
      DB_PASSWORD: SasaSasera1
      DB_ROOT_PASSWORD: SasaSasera1
      DB_USER: root
      JWT_SECRET: V3RY#1MP0RT@NT$$3CR3T#
      MYSQL_DATABASE: bluecity_dev
      MYSQL_PASSWORD: SasaSasera1
      MYSQL_ROOT_PASSWORD: SasaSasera1
      MYSQL_USER: root
      NODE_ENV: development
    image: mysql
    networks:
      app-network: null
    ports:
    - published: 3306
      target: 3306
    volumes:
    - my-db:/var/lib/mysql:rw
version: '3.3'
volumes:
  my-db:
    driver: local

